services: 
  db:
    image: postgres
    container_name: never-red-db
    environment: 
      NEVER_RED_DB_NAME: ${NEVER_RED_DB_NAME}

      POSTGRES_USER: root
      POSTGRES_PASSWORD: root-secret-password

      NEVER_RED_ADMIN_USER: ${NEVER_RED_ADMIN_USER}
      NEVER_RED_ADMIN_PWD: ${NEVER_RED_ADMIN_PWD}

      NEVER_RED_USER: ${NEVER_RED_USER}
      NEVER_RED_PWD: ${NEVER_RED_PWD}

    env_file:
      - .env
    ports:
      - 5434:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${POSTGRES_HOST}",  "-p", "${POSTGRES_PORT}"]
      interval: 1s
      timeout: 30s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"

  web:
    container_name: never-red-app
    env_file:
      - .env
    build: .
    ports:
      - 8000:9000
    depends_on:
      db: 
        condition: service_healthy

volumes:
  db-data:
