services: 
  web:
    container_name: never-red-app
    env_file:
      - .env
    build: .
    ports:
      - 8000:9000
    depends_on:
      db: 
        condition: service_healthy

  db:
    image: postgres
    container_name: never-red-db
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root-secret-password
    env_file:
      - .env
    ports:
      - 5433:${POSTGRES_PORT}
    volumes:
      - db-data:/etc/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${POSTGRES_HOST}",  "-p", "${POSTGRES_PORT}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db-data:
