version: "3.8"
services:
  web:
    container_name: never-red-web
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest 
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_USER: ${NEVER_RED_ADMIN_USER}
      POSTGRES_PASSWORD: ${NEVER_RED_ADMIN_PWD}
      POSTGRES_DB: ${NEVER_RED_DB_NAME}

      NEVER_RED_USER: ${NEVER_RED_USER}
      NEVER_RED_PWD: ${NEVER_RED_PWD}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${POSTGRES_HOST}",  "-p", "${POSTGRES_PORT}"]
      interval: 1s
      timeout: 3s
      retries: 90
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"

