version: "2"
services:
  web:
    container_name: never-red-web
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - never-red-backend
  db:
    container_name: never-red-db
    image: postgres:latest 
    ports: 
      - "5432:5432"
    networks:
      - never-red-backend
  
networks:
  never-red-backend:
