version: "2"
services:
  web:
    container_name: never-red-web
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    networks:
      - never-red-backend
  db:
    container_name: never-red-db
    image: postgres:latest 
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_USER: ${NEVER_RED_ADMIN_USER}
      POSTGRES_PASSWORD: ${NEVER_RED_ADMIN_PWD}
      POSTGRES_DB: ${NEVER_RED_DB_NAME}

      NEVER_RED_USER: ${NEVER_RED_USER}
      NEVER_RED_PWD: ${NEVER_RED_PWD}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - never-red-backend
  
networks:
  never-red-backend:
