name: build-and-test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  # The "build" job
  build:

    # The runner type
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # The sequence of tasks
    steps:

    # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: make build
      continue-on-error: false

    # Run vet & lint on the code
    - name: Run vet & lint
      run: make vet
      continue-on-error: false
      
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    
    steps: 

    - name: Test
      run: make test
